import Head from 'next/head'
// import Image from 'next/image'
import Converter from '../components/Converter'
import styles from '../styles/Home.module.css'
import React from 'react'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <Converter />
      </div>
      <footer className={styles.footer}>
        <a href="#" rel="noopener noreferrer">
          Powered by Kotkoa!
        </a>
      </footer>
    </div>
  )
}
